In [1]:
import numpy as np

In [2]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "python"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'python'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> int64 (4, 3)


In [3]:
# Create 
arr3 = np.zeros((2, 3), dtype="int64")  # prefill
print(arr3, arr3.shape)

arr4 = np.ones((5, ), dtype="int64")   # prefill
print(arr4, arr4.shape)

arr5 = np.full((3, 4), 100, dtype="int64")   # prefill with value
print(arr5, arr5.shape)

arr6 = np.eye(3, dtype="int64")   # identity matrix
print(arr6, arr6.shape)

arr7 = np.arange(1, 10, 2)     # range elements (start, end, step)
print(arr7, arr7.shape)

arr8 = np.linspace(1, 100, 4)   # evenly spaced arrays
print(arr8, arr8.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [ ]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)    # dimensions = m x n
print(arr.size)     # total elements
print(arr.dtype)    # datatype
print(arr.ndim)     # no. of dimension values

float_arr = arr.astype(np.float64)  # typecasting
print(float_arr, float_arr.dtype)

In [ ]:
# Operations on arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()   # 2D => 1D
print(flattened, flattened.shape)

In [ ]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])   # 1
print(arr[3])   # 4

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D[1][1])  # 5
print(arr2D[0][2])  # 3

# Fancy indexing
arr3 = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])     # [1 2 4]

# Boolean Indexing
arr4 = np.array([1, 2, 3, 4, 5])
print(arr[arr % 2 == 0])    # [2 4]

In [ ]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4:2]) # [start, end, step] Output => [2 4]
print(arr[1:])      # [2 3 4 5]
print(arr[:4])      # [1 2 3 4]
print(arr[:])       # [1 2 3 4 5]
print(arr[::])      # [1 2 3 4 5]
print(arr[::2])     # [1 3 5]

In [ ]:
# Data types
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)

arr2 = np.array([1, 2, 3.14, 4, 5])
print(arr2, arr2.dtype)

arr3 = np.array([1, 2, 3, 4, 5, "python"])
print(arr3, arr3.dtype)

arr4 = np.array([3 + 5j])
print(arr4, arr4.dtype)

arr5 = np.array([2 + 7j])
print(arr4 + arr5)
print(arr4 - arr5)

arr6 = np.array(["python", {1, 2, 3}, 3.14])
print(arr6, arr6.dtype)

In [ ]:
# Multi-dimensional arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))    # 45

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)   # [12 15 18]

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)      # [ 6 15 24]

print(arr2D[0:2, 1:2])  # [[2]
                        #  [5]]