In [22]:
import numpy as np

In [23]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "python"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'python'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> int64 (4, 3)


In [24]:
# Create 
arr3 = np.zeros((2, 3), dtype="int64")  # prefill
print(arr3, arr3.shape)

arr4 = np.ones((5, ), dtype="int64")   # prefill
print(arr4, arr4.shape)

arr5 = np.full((3, 4), 100, dtype="int64")   # prefill with value
print(arr5, arr5.shape)

arr6 = np.eye(3, dtype="int64")   # identity matrix
print(arr6, arr6.shape)

arr7 = np.arange(1, 10, 2)     # range elements (start, end, step)
print(arr7, arr7.shape)

arr8 = np.linspace(1, 100, 4)   # evenly spaced arrays
print(arr8, arr8.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [25]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)    # dimensions = m x n
print(arr.size)     # total elements
print(arr.dtype)    # datatype
print(arr.ndim)     # no. of dimension values

float_arr = arr.astype(np.float64)  # typecasting
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [26]:
# Operations on arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()   # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [27]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])   # 1
print(arr[3])   # 4

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D[1][1])  # 5
print(arr2D[0][2])  # 3

# Fancy indexing
arr3 = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])     # [1 2 4]

# Boolean Indexing
arr4 = np.array([1, 2, 3, 4, 5])
print(arr[arr % 2 == 0])    # [2 4]

1
4
5
3
[1 2 4]
[2 4]


In [28]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4:2]) # [start, end, step] Output => [2 4]
print(arr[1:])      # [2 3 4 5]
print(arr[:4])      # [1 2 3 4]
print(arr[:])       # [1 2 3 4 5]
print(arr[::])      # [1 2 3 4 5]
print(arr[::2])     # [1 3 5]

[2 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [29]:
# Data types
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)

arr2 = np.array([1, 2, 3.14, 4, 5])
print(arr2, arr2.dtype)

arr3 = np.array([1, 2, 3, 4, 5, "python"])
print(arr3, arr3.dtype)

arr4 = np.array([3 + 5j])
print(arr4, arr4.dtype)

arr5 = np.array([2 + 7j])
print(arr4 + arr5)
print(arr4 - arr5)

arr6 = np.array(["python", {1, 2, 3}, 3.14])
print(arr6, arr6.dtype)

[1 2 3 4 5] int64
[1.   2.   3.14 4.   5.  ] float64
['1' '2' '3' '4' '5' 'python'] <U21
[3.+5.j] complex128
[5.+12.j]
[1.-2.j]
['python' {1, 2, 3} 3.14] object


In [30]:
# Multi-dimensional arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))    # 45

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)   # [12 15 18]

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)      # [ 6 15 24]

print(arr2D[0:2, 1:2])  # [[2]
                        #  [5]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [31]:
# 3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])   # 2 x 3 x 2

print(arr3D, arr3D.shape)

# Indexing
print(arr3D[0, 1, 1])   # 4
print(arr3D[1, 1, 0])   # 9

# Slicing
print(arr3D[:, 0, :])   # first row from both layers
print(arr3D[:, :, 0])   # first column from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [32]:
# Vectorization
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr ** 2)     # [ 1  4  9 16 25]
print(arr + 10)     # [11 12 13 14 15]
print(arr + arr2)   # [ 7  9 11 13 15]

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [33]:
# Broadcasting
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr + 5)      # [ 6  7  8  9 10]
print(arr + arr2)   # [[ 2  4  6  8 10]
                    #  [ 2  4  6  8 10]]

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [34]:
# Normalization
arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

print(mean)             # 2.5
print(std_dev)          # 1.118033988749895

normalized_arr = (arr - mean) / std_dev
print(normalized_arr)   # [[-1.34164079 -0.4472136 ]
                        #  [ 0.4472136   1.34164079]]

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [35]:
# Aggregation Functions
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))      # 15
print(np.prod(arr))     # 120
print(np.min(arr))      # 1
print(np.max(arr))      # 5
print(np.argmin(arr))   # 0 -> returns index(min)
print(np.argmax(arr))   # 4 -> returns index(max)

print(np.mean(arr))     # 3.0
print(np.std(arr))      # 1.4142135623730951
print(np.median(arr))   # 3.0
print(np.var(arr))      # 2.0

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [36]:
# Power Functions
arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))   # [ 1  4  9 16 25]
print(np.sqrt(arr))     # [1.         1.41421356 1.73205081 2.         2.23606798]
print(np.pow(arr, 3))   # [  1   8  27  64 125]

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [37]:
# Log & Exponential Functions
arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))      # [0.         0.69314718 1.09861229 1.38629436 1.60943791]
print(np.log10(arr))    # [0.         0.30103    0.47712125 0.60205999 0.69897   ]
print(np.log2(arr))     # [0.         1.         1.5849625  2.         2.32192809]
print(np.exp(arr))      # [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [38]:
# Rounding Functions

print(np.round(3.57))       # 4.0
print(np.ceil(3.14))        # 4.0 -> round up
print(np.floor(3.89))       # 3.0 -> round down
print(np.trunc(3.14))       # 3.0 -> cuts the decimal value

4.0
4.0
3.0
3.0


In [39]:
# Extra Functions
arr = np.array([5, -2, 4, 4, -3, 1, -2, 5, -5, -4])

print(np.unique(arr))       # [-5 -4 -3 -2  1  4  5]
print(np.sort(arr))         # [-5 -4 -3 -2 -2  1  4  4  5  5]
print(np.abs(arr))          # [5 2 4 4 3 1 2 5 5 4]

[-5 -4 -3 -2  1  4  5]
[-5 -4 -3 -2 -2  1  4  4  5  5]
[5 2 4 4 3 1 2 5 5 4]
